version: "3"
services:
  app:
    build:
      context: .
    container_name: app_production
    command: ["npm", "run", "build"]
    
  nginx:
    image: nginx
    volumes:
      # - ./:/www/data/
      - ./dist/:/usr/share/nginx/html/
    ports:
      - 81:80
    depends_on:
      - app